function make
c = computer;
switch c
    case 'MACI64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Darwin-x86_64/libmetis ...
                -lmetis metismex.c -D__thread= -DLINUX
    case 'GLNXA64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Linux-x86_64/libmetis ...
                -lmetis metismex.c -DLINUX CFLAGS="\$CFLAGS -std=c99" ...
                -D_POSIX_C_SOURCE=200809

    case 'GLNX32'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/Linux-x86/libmetis ...
                -lmetis metismex.c -DLINUX

    case 'PCWIN64'
        mex -O -largeArrayDims -I../include -I../libmetis ...
                -I../GKlib -L../build/libmetis/Release ...
                -lmetis metismex.c -D__thread=__declspec(thread) ...
                -DWIN32 -DMSC -D_CRT_SECURE_NO_DEPRECATE -DUSE_GKREGEX
end
test_main